- name: deps
  description: "Dependency updates"
  color: "0366d6" # blue

- name: npm
  description: "npm package bumps"
  color: "cb0000" # red

- name: actions
  description: "GitHub Actions version bumps"
  color: "8a2be2" # purple
